version: '3'

services:
  web:
    build: .
    environment:
      - TRACING_HOST=jaeger
      - TRACING_PORT=6831
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # network_mode: host
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mltdemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this password
    depends_on:
      - loki
      - prometheus
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.32
    ports:
      - 16686:16686
      - 6831:6831

  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml --web.enable-lifecycle

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    depends_on:
      - promtail

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail:/etc/promtail
      - ./logs:/var/log
    command: --config.file=/etc/promtail/promtail.yaml
    depends_on:
      - web

volumes:
  postgres_data:

