global:
  scrape_interval: 10s
  # scrape_timeout: 30s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: dajngo-app
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'web:8000'
        labels:
          app: web
