# Generated by Django 4.2.3 on 2023-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_device_created_date_alter_device_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="modified_date",
            field=models.DateField(blank=True),
        ),
    ]
